import React from 'react';
import list from '../constants/_typeList'

/*
  THE TASK - 
  
  1. CREATE CODE, THAT, WHEN RUN, WILL DISPLAY, AS A FUNCTIONAL REACT
  COMPONENT, THE SUMMED-UP COUNT OF ALL THE DIFFERENT TYPES OF CONTENT
  FROM THE _typeList.js FILE AS A LIST, LIKE THIS:

  E-Learning: XX, 
  Article: XX...

  THIS INCLUDES DATA RESHAPING OF THE ARRAY IN A WAY THAT SIMPLIFIES
  THE COMPONENT THE MOST (note: you only need 1 function call for this)

  2. ADD A COUNTER THAT GOES UP EVERYTIME YOU PRESS THE 'f' KEY, DISPLAYED
  IN A COMPONENT ON SCREEN.

  MAKE SURE THAT WHEN YOU GO BETWEEN THE ROUTES AND BACK, THAT
  THERE IS NO MEMORY LEAK IN THE APP

  NO EXTERNAL PACKAGES USED. EVERYTHING IS SOLVED WITH REGULAR JS AND REACT
*/

export default () => {
  // WRITE YOUR CODE HERE
  return null
}